In [50]:
import spacy
nlp = spacy.load('da_core_news_md')
#print(nlp.Defaults.stop_words) # A set of stopwords

# ',' and '.' added
# ADD STOP-WORD ','
#nlp.Defaults.stop_words.add(',')
#nlp.vocab[','].is_stop = True
#nlp.vocab[','].is_stop

# ADD STOP-WORD '.'
#nlp.Defaults.stop_words.add('ét')
#nlp.vocab['ét'].is_stop = True
#nlp.vocab['ét'].is_stop

# REMOVE STOP-WORDS ','
#nlp.Defaults.stop_words.remove(',')
#nlp.vocab[','].is_stop = False
#nlp.vocab[','].is_stop 

print(sorted(nlp.Defaults.stop_words))
print(len(nlp.Defaults.stop_words))

['af', 'aldrig', 'alene', 'alle', 'allerede', 'alligevel', 'alt', 'altid', 'anden', 'andet', 'andre', 'at', 'bag', 'begge', 'blandt', 'blev', 'blive', 'bliver', 'burde', 'bør', 'da', 'de', 'dem', 'den', 'denne', 'dens', 'der', 'derefter', 'deres', 'derfor', 'derfra', 'deri', 'dermed', 'derpå', 'derved', 'det', 'dette', 'dig', 'din', 'dine', 'disse', 'dog', 'du', 'efter', 'egen', 'eller', 'ellers', 'en', 'end', 'endnu', 'ene', 'eneste', 'enhver', 'ens', 'enten', 'er', 'et', 'flere', 'flest', 'fleste', 'for', 'foran', 'fordi', 'forrige', 'fra', 'få', 'før', 'først', 'gennem', 'gjorde', 'gjort', 'god', 'gør', 'gøre', 'gørende', 'ham', 'han', 'hans', 'har', 'havde', 'have', 'hel', 'heller', 'hen', 'hende', 'hendes', 'henover', 'her', 'herefter', 'heri', 'hermed', 'herpå', 'hun', 'hvad', 'hvem', 'hver', 'hvilke', 'hvilken', 'hvilkes', 'hvis', 'hvor', 'hvordan', 'hvorefter', 'hvorfor', 'hvorfra', 'hvorhen', 'hvori', 'hvorimod', 'hvornår', 'hvorved', 'i', 'igen', 'igennem', 'ikke', 'imellem',

In [9]:
import pandas as pd
header_names=['text']
npr = pd.read_csv('descriptions.csv', header=None, skiprows=1, names=header_names, sep='\n')

import spacy
nlp = spacy.load('da_core_news_sm')
stopord = nlp.Defaults.stop_words  # stop_words is a set
#print(len(stopord)) # 221 stop_words

def normalize(comment, lowercase, remove_stopwords):
    if lowercase:
        comment = comment.lower()
    comment = nlp(comment)
    lemmatized = list()
    for word in comment:
        lemma = word.lemma_.strip()
        if lemma:
            if not remove_stopwords or (remove_stopwords and lemma not in stopord):
                lemmatized.append(lemma)
    return " ".join(lemmatized)

npr['text2']=npr['text'].apply(normalize, lowercase=True, remove_stopwords=True)
npr['text3'] = npr['text2'].str.replace('[^\w\s]','')
npr['text4'] = npr['text3'].str.replace('[0-9]','')
print(npr['text4'])
[print(item) for item in npr['text4']]


#words = 'ndværker' 
#selection1 = npr['text4'].str.contains(words)
#print(selection1) # VIRKER
#print("\nNumber of texts containing the word {} :".format(words), len(selection1))



#new_df = npr['text4'].to_csv('text4.csv', index=False)

ties  kaelderlokaleivelbeliggendeejendomikendtindustrikvarter
megen velbeliggende ejendom tætte stor indfaldsvej motorvej ring  ejendom bestå  enhed  hvoraf  ledig pt mulighed højloftet lage  mede stor bred ledhejseport  samt produktionslokale mede port  enestående mulighed attraktiv lejemål glostrup motorvej ring  ring  ligge ligeledes tætte komme letbane  ejendom bruge formål enhed måtte vælge  forbygningen optimal løsning håndværker virksomhed behov godte showroom  lysindfald side  give optimal mulighed præsentation produkt  herudover mulighed leje gode højloftet lagerlejemål  loftshøjde ca  m  lejemål adgang terræn mede ledhejsport  lejemål overtage mede hvidmalet væg loft  lejemål følge størrelse   m² godte lyst lejemål mede høj loft  tilkørsel ske terræn port   m² godte stor lejemål mede indgang stor bred port  indskyde dæk  evt nedtage   m² administrationsbygning  mede loftshøjde ca  m enkelt kontor køkken toilet  port terræn ende bygning   m² beligge kælder indgang trappe  vare

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,

In [10]:
# The condition of the house
import pandas as pd
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize

header_names=['text']
df = pd.read_csv('descriptions.csv', header=None, skiprows=1, names=header_names, sep='\n')

condition_house =['håndværkertilbud', 'nedrivning', 'dårlig stand']
#location = ['beliggenhed', 'udsigt']

df['text'] = df['text'].apply(lambda text: [sent for sent in sent_tokenize(text)
if any(True for w in word_tokenize(sent) 
if w.lower() in condition_house)])

df1 = df.applymap(lambda x: [y for y in x if len(y) > 0])
df1 = df1[df1.applymap(len).ne(0).all(axis=1)]

print(f"No. of texts containing the word 'håndværkertilbud', 'nedrivning' or 'dårlig stand' : {len(df1)}")
print(df1)

No. of texts containing the word 'håndværkertilbud', 'nedrivning' or 'dårlig stand' : 27
                                                   text
50    [Så er der dømt håndværkertilbud for alle peng...
311   [HÅNDVÆRKERTILBUD MED BYGGETILLADELSEØgadekvar...
485   [# Staldbygning fra 1918 med et erhvervsareal ...
487   [Eller til nedrivning og fa bygget lige det hu...
625   [Huset sælges som et "håndværkertilbud", og sæ...
704   [VALBY -  HÅNDVÆRKERTILBUD - MÅSKE DRØMMER DU ...
740   [Ejendommen sælges med henblik på nedrivning, ...
929   [Villaen trænger til en kærlig hånd og køber s...
1057  [VALBY -  HÅNDVÆRKERTILBUD - MÅSKE DRØMMER DU ...
1094  [Der er vel tale om det man kan kalde et håndv...
1351  [På ejendommen ligger idag et gammelt hus, tje...
1413  [Der er et ældre hus beliggende på matriklen d...
1636  [Huset sælges som et "håndværkertilbud", og sæ...
1656  [Denne etværelses ejerlejlighed på 39 kvadratm...
1806  [Ældre sommerhus ved Grenaa Strand til nedrivn...
1810  [På Fjord

In [11]:
# The location of the plot
import pandas as pd
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize

header_names=['text']
df = pd.read_csv('descriptions.csv', header=None, skiprows=1, names=header_names, sep='\n')

location = ['beliggenhed', 'placering']

df['text'] = df['text'].apply(lambda text: [sent for sent in sent_tokenize(text)
if any(True for w in word_tokenize(sent) 
if w.lower() in location)])

df1 = df.applymap(lambda x: [y for y in x if len(y) > 0])
df1 = df1[df1.applymap(len).ne(0).all(axis=1)]

print(f"No. of texts containing the word 'beliggenhed' or 'udsigt' stand : {len(df1)}")
print(df1)
print(df1['text'][3])

No. of texts containing the word 'beliggenhed' or 'udsigt' stand : 693
                                                   text
0     [Den nuværende planløsning er ideel til parret...
3     [Meget rummelig etplansvilla med god beliggenh...
4     [Beliggenhed: Tæt på havet syd for Skagen, i Å...
13    [Denne store, skønne villa ligger i Hedehusene...
15    [Det særlige er den naturnære fornemmelse, som...
...                                                 ...
2475                  [Bedste beliggenhed i bykernen !]
2476  [Ejendommen har en god beliggenhed mellem Hors...
2485  [Lejemålet har en central placering med Nuuks ...
2489                [God beliggenhed i Horsens midtby.]
2495  [CHARMERENDE RØDSTENSVILLA TIL DEN LILLE FAMIL...

[693 rows x 1 columns]
['Meget rummelig etplansvilla med god beliggenhed i det eftertragtede Eriksmindekvarter nær skole, indkøb, Greve Idrætscenter, offentlig transport samt gode stisystemer til Waves indkøbscenter, S-station samt flot badestrand.']


In [12]:
import pandas as pd
header_names=['text']
npr = pd.read_csv('descriptions.csv', header=None, skiprows=1, names=header_names, sep='\n')
#npr.head()
#npr['text'][0]


from nltk.corpus import stopwords
dansk = stopwords.words('danish')
print(len(dansk))
#npr['text'][0].split(' ').apply(lambda x: [item for item in x if item not in dansk])


input = npr['text'][0].split(' ')
mylist = []
for i in input:
    if i not in dansk:
        i = i.lower()
        mylist.append(i) 
print(mylist)





94
['i', 'populære', 'paarup', 'udbydes', 'dejlig', 'villa', 'ét', 'plan,', 'husets', 'muligheder', 'ingen', 'begrænsninger', 'har.', 'huset', 'velholdt,', 'lyst', 'imødekommende', 'giver', 'godt', 'helhedsindtryk', 'start', 'slut.', 'den', 'nuværende', 'planløsning', 'ideel', 'parret', 'lille', 'familie,', 'hus', 'helt', 'ekseptionelt', 'god', 'beliggenhed.', 'ejendommen', 'ude', 'inde', 'velholdt', 'lige', 'gå', 'til.', 'huset', 'rummer', 'dejligt', 'køkken,', 'ligger', 'opad', 'stue', 'udestue', '-', 'andre', 'ord', 'kan', 'let', 'hurtigt', 'gøre', 'drømmen', 'køkkenalrum', 'virkelighed.', 'endvidere', 'findes', 'dejligt', 'rummeligt', 'bryggers,', 'dagligdagen', 'fungerer', 'praktisk', 'indgang.', 'husets', 'to', 'store', 'værelser', 'ligger', 'forlængelse', 'nuværende', 'spisestue.', 'det', 'ene', 'værelse', 'oprindeligt', 'to,', 'få', 'store', 'åbne', 'rum,', 'sidenhen', 'prioriteret', 'to', 'store', 'værelser', 'stedet.', 'dette', 'kan', 'let', 'reetableres,', 'så', 'huset', 'ru

In [13]:
import pandas as pd
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize

header_names=['text']
df = pd.read_csv('descriptions.csv', header=None, skiprows=1, names=header_names, sep='\n')

location = ['beliggenhed', 'placering']

df['text'] = df['text'].apply(lambda text: [sent for sent in sent_tokenize(text)
if any(True for w in word_tokenize(sent) 
if w.lower() in location)])

df1 = df.applymap(lambda x: [y for y in x if len(y) > 0])
df1 = df1[df1.applymap(len).ne(0).all(axis=1)]

print(f"No. of texts containing the word 'beliggenhed' or 'udsigt' stand : {len(df1)}")
print(df1)
print(df1['text'][3])

from nltk.corpus import stopwords # stopwords overflødig
import spacy
nlp = spacy.load('da_core_news_sm')
dansk = nlp.Defaults.stop_words

#dansk = stopwords.words('danish')
print(len(dansk))

#from sklearn.feature_extraction.text import CountVectorizer
#cv = CountVectorizer(max_df=0.9, min_df=2, stop_words=dansk)
#dtm = cv.fit_transform(df['text'])
#dtm

#npr['text'][0]
#from nltk.corpus import stopwords
#dansk = stopwords.words('danish')        # INDSÆT DE OPRINDELIGE STOPORD

No. of texts containing the word 'beliggenhed' or 'udsigt' stand : 693
                                                   text
0     [Den nuværende planløsning er ideel til parret...
3     [Meget rummelig etplansvilla med god beliggenh...
4     [Beliggenhed: Tæt på havet syd for Skagen, i Å...
13    [Denne store, skønne villa ligger i Hedehusene...
15    [Det særlige er den naturnære fornemmelse, som...
...                                                 ...
2475                  [Bedste beliggenhed i bykernen !]
2476  [Ejendommen har en god beliggenhed mellem Hors...
2485  [Lejemålet har en central placering med Nuuks ...
2489                [God beliggenhed i Horsens midtby.]
2495  [CHARMERENDE RØDSTENSVILLA TIL DEN LILLE FAMIL...

[693 rows x 1 columns]
['Meget rummelig etplansvilla med god beliggenhed i det eftertragtede Eriksmindekvarter nær skole, indkøb, Greve Idrætscenter, offentlig transport samt gode stisystemer til Waves indkøbscenter, S-station samt flot badestrand.']
219


In [14]:
#  ****   LDA   ****

import pandas as pd
header_names=['text']
npr = pd.read_csv('descriptions.csv', header=None, skiprows=1, names=header_names, sep='\n')
npr['text'][0]

'I det populære Paarup udbydes her en dejlig villa i ét plan, hvor husets muligheder ingen begrænsninger har. Huset er velholdt, lyst og imødekommende og giver et godt helhedsindtryk fra start til slut. Den nuværende planløsning er ideel til parret eller den lille familie, der vil have hus og have og en helt ekseptionelt god beliggenhed. Ejendommen ude som inde er velholdt og lige til at gå til. Huset rummer et dejligt køkken, som ligger opad stue og udestue - med andre ord kan du let og hurtigt gøre drømmen om et køkkenalrum til virkelighed. Endvidere findes et dejligt rummeligt bryggers, der i dagligdagen fungerer som praktisk indgang. Husets to store værelser ligger i forlængelse af den nuværende spisestue. Det ene værelse har oprindeligt været to, men for at få store og åbne rum, er der sidenhen prioriteret to store værelser i stedet. Dette kan let reetableres, så huset vil rumme to børneværelser og ét forældresoveværelse. Og netop sidstnævnte har eget badeværelse, mens der fra spi

In [15]:
import spacy
nlp = spacy.load('da_core_news_sm')
stopord = nlp.Defaults.stop_words 


In [16]:
print(len(stopord), '\n')
for v in stopord:
    print(v)

219 

synes
er
nogle
derefter
på
øvrigt
dermed
min
hvornår
vær
han
mest
ikke
hvilkes
måske
om
stadig
så
men
ens
ind
allerede
ingen
langs
nogen
udover
hvad
igen
blandt
intet
herpå
enten
lidt
hvor
ny
tilbage
hvilken
os
derfra
dens
og
mine
igennem
andet
deri
mere
tidligere
i
der
lavet
mindre
ned
siden
for
flest
nemlig
har
længere
hende
end
heller
mellem
herefter
kommer
din
hvorfor
til
da
hvem
disse
egen
kan
op
skulle
over
under
undtagen
lav
at
nok
altid
heri
sige
kunne
uden
hvorefter
den
gennem
lave
bliver
eneste
gjorde
hermed
hvori
kun
her
bag
vores
eller
nær
dem
det
andre
næste
mens
derved
nyt
denne
god
sammen
jeres
alligevel
lille
kom
få
lad
syntes
ud
vi
gøre
ved
hendes
gør
gørende
jer
man
hvordan
fra
forrige
deres
begge
skal
hun
nu
dog
været
de
også
mange
ene
mit
fordi
alene
før
du
først
være
hen
ligesom
næsten
via
hver
selvom
samme
sådan
et
vil
hel
må
alle
enhver
senere
hvorfra
indtil
selv
derpå
ses
mindst
en
som
efter
nogensinde
ville
meget
vore
blev
aldrig
alt
imellem
foran
hvilke


In [17]:
 

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_df=0.9, min_df=2, stop_words=stopord) # Kan man indsætte stopord her i stedet for 'danish'?
dtm = cv.fit_transform(npr['text'])
dtm


<2500x14665 sparse matrix of type '<class 'numpy.int64'>'
	with 300363 stored elements in Compressed Sparse Row format>

In [18]:
from sklearn.decomposition import LatentDirichletAllocation
LDA = LatentDirichletAllocation(n_components=7, random_state=42)
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [19]:
len(cv.get_feature_names())

14665

In [20]:
import random
random_word_id = random.randint(0,14665)
cv.get_feature_names()[random_word_id] 

'badeværelseet'

In [21]:
# Grab the topics
len(LDA.components_)

7

In [22]:
type(LDA.components_)

numpy.ndarray

In [23]:
LDA.components_.shape
LDA.components_

array([[11.4226676 , 54.31992352,  0.14285715, ...,  0.14285716,
         0.14285716, 22.59478247],
       [13.33561856, 31.42695803,  0.14285715, ...,  2.14259678,
         1.14270099,  4.46022081],
       [ 0.1430647 ,  0.14301087,  0.14285716, ...,  0.14310637,
         0.14285722,  3.80519134],
       ...,
       [ 2.34175836, 30.65530585,  0.14285715, ...,  0.14285719,
         0.14439494, 21.94661146],
       [17.34706821,  8.68879763,  0.14294516, ...,  4.1409401 ,
         0.14285716, 12.57905577],
       [ 7.85577804, 37.75344134,  0.14290841, ...,  0.14367658,
         0.14285715, 43.84880529]])

In [24]:
single_topic = LDA.components_[0]
single_topic.argsort()

array([ 6344,  8141,  9209, ...,  3778, 10887,  8965], dtype=int64)

In [25]:
import numpy as np
arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [26]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [27]:
# grab the last 10 values of .argsort()

single_topic.argsort()[-10:] 

array([ 8473,  9583, 12043, 14305,  6388,  2027,  7808,  3778, 10887,
        8965], dtype=int64)

In [28]:
top_ten_words = single_topic.argsort()[-10:]
for index in top_ten_words:
    print(cv.get_feature_names()[index])

m2
opført
stor
værelser
huset
badeværelse
køkken
ejendommen
samt
m²


In [29]:
# Grab the highest probability words per topic

for i, topic in enumerate(LDA.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['adgang', 'stue', 'udgang', 'gode', 'www', 'm2', 'opført', 'stor', 'værelser', 'huset', 'badeværelse', 'køkken', 'ejendommen', 'samt', 'm²']




THE TOP 15 WORDS FOR TOPIC #1
['plads', 'stue', 'terrasse', 'udgang', 'kvm', 'beliggende', 'bryggers', 'www', 'store', 'stor', 'stort', 'huset', 'badeværelse', 'samt', 'køkken']




THE TOP 15 WORDS FOR TOPIC #2
['kontakt', 'store', 'godt', 'sag', 'udsigt', 'lilienhoff', 'helt', 'mod', 'minutter', 'salg', 'href', 'bolig', 'www', 'ejendommen', 'ligger']




THE TOP 15 WORDS FOR TOPIC #3
['stue', 'aarhus', 'mod', 'helt', 'bolig', 'får', 'altan', 'både', 'store', 'plads', 'ligger', 'to', 'lejlighed', 'køkken', 'lejligheden']




THE TOP 15 WORDS FOR TOPIC #4
['ligger', 'huset', 'ejendomme', 'www', 'c3', 'kontor', 'mulighed', 'grunden', 'området', 'ca', 'gode', 'samt', 'lejemålet', 'beliggende', 'ejendommen']




THE TOP 15 WORDS FOR TOPIC #5
['soveværelse', 'flot', 'beliggende', 'store', 'ejendommen', 'gode', 'lejli

In [30]:
dtm

<2500x14665 sparse matrix of type '<class 'numpy.int64'>'
	with 300363 stored elements in Compressed Sparse Row format>

In [31]:
topic_results = LDA.transform(dtm)
topic_results[0].round(2)

array([0.  , 0.08, 0.  , 0.  , 0.  , 0.06, 0.85])

In [32]:
npr['text'][0]

'I det populære Paarup udbydes her en dejlig villa i ét plan, hvor husets muligheder ingen begrænsninger har. Huset er velholdt, lyst og imødekommende og giver et godt helhedsindtryk fra start til slut. Den nuværende planløsning er ideel til parret eller den lille familie, der vil have hus og have og en helt ekseptionelt god beliggenhed. Ejendommen ude som inde er velholdt og lige til at gå til. Huset rummer et dejligt køkken, som ligger opad stue og udestue - med andre ord kan du let og hurtigt gøre drømmen om et køkkenalrum til virkelighed. Endvidere findes et dejligt rummeligt bryggers, der i dagligdagen fungerer som praktisk indgang. Husets to store værelser ligger i forlængelse af den nuværende spisestue. Det ene værelse har oprindeligt været to, men for at få store og åbne rum, er der sidenhen prioriteret to store værelser i stedet. Dette kan let reetableres, så huset vil rumme to børneværelser og ét forældresoveværelse. Og netop sidstnævnte har eget badeværelse, mens der fra spi

In [33]:
topic_results[0].argmax()

6

In [45]:
npr['topic'] = topic_results.argmax(axis=1)
npr.head()

text  topic     Topic Label
0  I det populære Paarup udbydes her en dejlig vi...      6   et sjete emne
1  Går du med en drøm om at lave din helt egen bo...      4  et fjerde emne
2  Ejendommen befinder sig i naturskønne Sdr. Vis...      4  et fjerde emne
3  Meget rummelig etplansvilla med god beliggenhe...      5   et femte emne
4  Beliggenhed: Tæt på havet syd for Skagen, i Ål...      4  et fjerde emne

In [44]:
mytopic_dict = {0:'Rum',1:'plads',2:'placering',3:'et tredje emne',4:'et fjerde emne',5:'et femte emne',6:'et sjete emne'}
npr['Topic Label'] = npr['topic'].map(mytopic_dict)
npr.head(10)

text  topic     Topic Label
0  I det populære Paarup udbydes her en dejlig vi...      6   et sjete emne
1  Går du med en drøm om at lave din helt egen bo...      4  et fjerde emne
2  Ejendommen befinder sig i naturskønne Sdr. Vis...      4  et fjerde emne
3  Meget rummelig etplansvilla med god beliggenhe...      5   et femte emne
4  Beliggenhed: Tæt på havet syd for Skagen, i Ål...      4  et fjerde emne
5  Egestien 2, 2950 VedbækDejlig etplansvilla i k...      1           plads
6  Nustrup er et velfungerende lokalsamfund med e...      6   et sjete emne
7  Gulstensvilla i det hyggelige Jersie. "Bo på l...      1           plads
8  Ejendommen er skønt beliggende i Smidstrup tæt...      0             Rum
9  Velkommen indenfor på denne flotte og hyggelig...      6   et sjete emne