In [4]:
import pandas as pd
header_names=['text']
npr = pd.read_csv('descriptions.csv', header=None, skiprows=1, names=header_names, sep='\n')
#npr.head()
#npr['text'][0]

from nltk.corpus import stopwords
dansk = stopwords.words('danish')
print(len(dansk))
#npr['text'][0].split(' ').apply(lambda x: [item for item in x if item not in dansk])
input = npr['text'][0].split(' ')
mylist = []
for i in input:
#    print(i)
    if i not in dansk:
        mylist.append(i) 
print(mylist)
        # LAV OM TIL LOWERCASE 

#import spacy
#nlp = spacy.load('da_core_news_sm')
#doc1 = nlp(str(mylist))  
#for token in doc1:
#    print(token.text, '\t',token.pos_,'\t', token.lemma,'\t',token.lemma_)
    
#temp = npr['text'][0]
#print(temp.split(' '))
#for item in npr['text']:
#    print('\n',item)
    
#npr['text'].apply(lambda x: [item for item in x if item not in dansk])
#print(npr['text'][0])

#from sklearn.feature_extraction.text import CountVectorizer
#cv = CountVectorizer(max_df=0.9, min_df=2, stop_words=dansk)
#dtm = cv.fit_transform(npr['text'])



94
['I', 'populære', 'Paarup', 'udbydes', 'dejlig', 'villa', 'ét', 'plan,', 'husets', 'muligheder', 'ingen', 'begrænsninger', 'har.', 'Huset', 'velholdt,', 'lyst', 'imødekommende', 'giver', 'godt', 'helhedsindtryk', 'start', 'slut.', 'Den', 'nuværende', 'planløsning', 'ideel', 'parret', 'lille', 'familie,', 'hus', 'helt', 'ekseptionelt', 'god', 'beliggenhed.', 'Ejendommen', 'ude', 'inde', 'velholdt', 'lige', 'gå', 'til.', 'Huset', 'rummer', 'dejligt', 'køkken,', 'ligger', 'opad', 'stue', 'udestue', '-', 'andre', 'ord', 'kan', 'let', 'hurtigt', 'gøre', 'drømmen', 'køkkenalrum', 'virkelighed.', 'Endvidere', 'findes', 'dejligt', 'rummeligt', 'bryggers,', 'dagligdagen', 'fungerer', 'praktisk', 'indgang.', 'Husets', 'to', 'store', 'værelser', 'ligger', 'forlængelse', 'nuværende', 'spisestue.', 'Det', 'ene', 'værelse', 'oprindeligt', 'to,', 'få', 'store', 'åbne', 'rum,', 'sidenhen', 'prioriteret', 'to', 'store', 'værelser', 'stedet.', 'Dette', 'kan', 'let', 'reetableres,', 'så', 'huset', 'ru

In [3]:
import pandas as pd
header_names=['text']
npr = pd.read_csv('descriptions.csv', header=None, skiprows=1, names=header_names, sep='\n')


from nltk.corpus import stopwords
dansk = stopwords.words('danish')
print(len(dansk))
#npr['text'][0].split(' ').apply(lambda x: [item for item in x if item not in dansk])


input = npr['text'][0].split(' ')
mylist = []
for i in input:
    if i not in dansk:
        i = i.lower()
        mylist.append(i) 
print(mylist)

94
['i', 'populære', 'paarup', 'udbydes', 'dejlig', 'villa', 'ét', 'plan,', 'husets', 'muligheder', 'ingen', 'begrænsninger', 'har.', 'huset', 'velholdt,', 'lyst', 'imødekommende', 'giver', 'godt', 'helhedsindtryk', 'start', 'slut.', 'den', 'nuværende', 'planløsning', 'ideel', 'parret', 'lille', 'familie,', 'hus', 'helt', 'ekseptionelt', 'god', 'beliggenhed.', 'ejendommen', 'ude', 'inde', 'velholdt', 'lige', 'gå', 'til.', 'huset', 'rummer', 'dejligt', 'køkken,', 'ligger', 'opad', 'stue', 'udestue', '-', 'andre', 'ord', 'kan', 'let', 'hurtigt', 'gøre', 'drømmen', 'køkkenalrum', 'virkelighed.', 'endvidere', 'findes', 'dejligt', 'rummeligt', 'bryggers,', 'dagligdagen', 'fungerer', 'praktisk', 'indgang.', 'husets', 'to', 'store', 'værelser', 'ligger', 'forlængelse', 'nuværende', 'spisestue.', 'det', 'ene', 'værelse', 'oprindeligt', 'to,', 'få', 'store', 'åbne', 'rum,', 'sidenhen', 'prioriteret', 'to', 'store', 'værelser', 'stedet.', 'dette', 'kan', 'let', 'reetableres,', 'så', 'huset', 'ru

In [15]:
from sklearn.decomposition import LatentDirichletAllocation
LDA =LatentDirichletAllocation(n_components=7,random_state=42)
LDA.fit(dtm)
print(LDA)

LatentDirichletAllocation(n_components=7, random_state=42)


In [25]:
# Grab the vocabulary of words
len(cv.get_feature_names())
#type(cv.get_feature_names())
#cv.get_feature_names()[50]

14781

In [26]:
import random
randomr_word_id = random.randint(0,14781)
cv.get_feature_names()[10]

'010'

In [29]:
# Grab the topic
LDA.components_.shape #(topics, components)

(7, 14781)

In [31]:
single_topic = LDA.components_[0]

print(single_topic.argsort())

[ 2727 14686 11537 ...  9049  3797  8128]


In [33]:
import numpy as np  
arr = np.array([10,200,1])
print(arr)
print(arr.argsort())

[ 10 200   1]
[2 0 1]


In [34]:
# ARGSORT ---> INDEX POSITIONS SORTED FROM LEAST --> GREATEST
# TOP 10 VALUES (10 GREATEST VALUES)
# LAST 10 VALUES of ARGSORT()
single_topic.argsort()[-10:] # grab the Last 10 values of .argsort()

array([ 8209,  2257,  8127,  7877,  7225, 14491, 10984,  9049,  3797,
        8128], dtype=int64)

In [41]:
top_ten_words = single_topic.argsort()[-10:]
for index in top_ten_words:
    print(cv.get_feature_names()[index])

ligger
beliggende
lejlighed
køkken
kan
www
samt
m²
ejendommen
lejligheden


In [44]:
# Grab the highest probability words per topic
for i,topic in enumerate(LDA.components_):
    print(f"THE TOP 10 WORDS FOR TOPIC #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-10:]])
    print('\n')
    print('\n')

THE TOP 10 WORDS FOR TOPIC #0
['ligger', 'beliggende', 'lejlighed', 'køkken', 'kan', 'www', 'samt', 'm²', 'ejendommen', 'lejligheden']




THE TOP 10 WORDS FOR TOPIC #1
['store', 'm2', 'stor', 'ved', 'www', 'beliggende', 'flot', 'kvm', 'ejendommen', 'samt']




THE TOP 10 WORDS FOR TOPIC #2
['mellem', '10', 'gode', 'home', 'samtidig', 'helt', 'kort', 'mulighed', 'lejligheden', 'kan']




THE TOP 10 WORDS FOR TOPIC #3
['sommerhus', 'beliggende', 'vesterhavet', 'ringkøbing', 'både', 'horsens', 'kan', 'ca', 'området', 'ligger']




THE TOP 10 WORDS FOR TOPIC #4
['plads', 'kan', 'stort', 'gode', 'stor', 'huset', 'køkken', 'badeværelse', 'god', 'samt']




THE TOP 10 WORDS FOR TOPIC #5
['både', 'store', 'ligger', 'plads', 'værelser', 'køkken', 'får', 'to', 'så', 'kan']




THE TOP 10 WORDS FOR TOPIC #6
['beliggende', 'mulighed', 'stue', 'klar', 'husene', 'boligerne', 'udbydes', 'boliger', 'bolig', 'køkken']






In [45]:
dtm

<2500x14781 sparse matrix of type '<class 'numpy.int64'>'
	with 320717 stored elements in Compressed Sparse Row format>

In [50]:
topic_results = LDA.transform(dtm)
topic_results.shape
topic_results[0].round(2)
topic_results[0].argmax()

5

In [56]:
npr['Topic'] = topic_results.argmax(axis=1)
print(npr)

                                                   text  Topic
0     I det populære Paarup udbydes her en dejlig vi...      5
1     Går du med en drøm om at lave din helt egen bo...      4
2     Ejendommen befinder sig i naturskønne Sdr. Vis...      4
3     Meget rummelig etplansvilla med god beliggenhe...      4
4     Beliggenhed: Tæt på havet syd for Skagen, i Ål...      0
...                                                 ...    ...
2495  CHARMERENDE RØDSTENSVILLA TIL DEN LILLE FAMILI...      5
2496  Rigtigt pænt og velholdt parcelhus beliggende ...      4
2497  Lige i hjertet af Valby finder du denne virkel...      4
2498  På Kragekærvej 5  lige der hvor vejen slår en ...      5
2499  Moderne velbygget og funktionel familievilla i...      4

[2500 rows x 2 columns]
