In [2]:
import pandas as pd
header_names=['text']
npr = pd.read_csv('descriptions.csv', header=None, skiprows=1, names=header_names, sep='\n')
#npr.head()


npr['text'][0]
#len(npr)

'I det populære Paarup udbydes her en dejlig villa i ét plan, hvor husets muligheder ingen begrænsninger har. Huset er velholdt, lyst og imødekommende og giver et godt helhedsindtryk fra start til slut. Den nuværende planløsning er ideel til parret eller den lille familie, der vil have hus og have og en helt ekseptionelt god beliggenhed. Ejendommen ude som inde er velholdt og lige til at gå til. Huset rummer et dejligt køkken, som ligger opad stue og udestue - med andre ord kan du let og hurtigt gøre drømmen om et køkkenalrum til virkelighed. Endvidere findes et dejligt rummeligt bryggers, der i dagligdagen fungerer som praktisk indgang. Husets to store værelser ligger i forlængelse af den nuværende spisestue. Det ene værelse har oprindeligt været to, men for at få store og åbne rum, er der sidenhen prioriteret to store værelser i stedet. Dette kan let reetableres, så huset vil rumme to børneværelser og ét forældresoveværelse. Og netop sidstnævnte har eget badeværelse, mens der fra spi

In [15]:
from nltk.corpus import stopwords
dansk = stopwords.words('danish')

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_df=0.9, min_df=2, stop_words=dansk)
dtm = cv.fit_transform(npr['text'])
dtm

<2500x14781 sparse matrix of type '<class 'numpy.int64'>'
	with 320717 stored elements in Compressed Sparse Row format>

In [16]:
for v in dansk:
    print(v)

og
i
jeg
det
at
en
den
til
er
som
på
de
med
han
af
for
ikke
der
var
mig
sig
men
et
har
om
vi
min
havde
ham
hun
nu
over
da
fra
du
ud
sin
dem
os
op
man
hans
hvor
eller
hvad
skal
selv
her
alle
vil
blev
kunne
ind
når
være
dog
noget
ville
jo
deres
efter
ned
skulle
denne
end
dette
mit
også
under
have
dig
anden
hende
mine
alt
meget
sit
sine
vor
mod
disse
hvis
din
nogle
hos
blive
mange
ad
bliver
hendes
været
thi
jer
sådan


In [6]:
from sklearn.decomposition import LatentDirichletAllocation
LDA = LatentDirichletAllocation(n_components=7, random_state=42)
LDA.fit(dtm)


LatentDirichletAllocation(n_components=7, random_state=42)

In [7]:
# Grab the vocabulary of words
len(cv.get_feature_names())
#cv.get_feature_names()[11000]


14781

In [8]:
import random
random_word_id = random.randint(0,14817)
cv.get_feature_names()[10]

'010'

In [16]:
# Grab the topics
len(LDA.components_)

7

In [9]:
type(LDA.components_)


numpy.ndarray

In [10]:
LDA.components_.shape
LDA.components_

array([[18.18460874, 91.21239532,  0.14300489, ...,  1.23685855,
        39.1336679 , 20.66895259],
       [ 0.50347686,  3.75339618,  0.14285715, ...,  0.14312445,
         3.37986955,  0.14310702],
       [ 0.14299275, 28.51615494,  4.14238868, ...,  0.14285716,
         0.5468756 ,  4.85165704],
       ...,
       [26.83925552, 22.82927186,  0.14294841, ...,  0.14285715,
        42.69796696, 11.39654502],
       [ 8.04385058,  6.43919484,  0.14308653, ...,  0.14285715,
        30.55742228, 42.65383939],
       [ 0.14294332, 19.54417523,  0.14285716, ...,  0.14285718,
         0.14325888,  0.14302355]])

In [11]:
single_topic = LDA.components_[0]
single_topic.argsort()

array([ 2727, 14686, 11537, ...,  9049,  3797,  8128], dtype=int64)

In [12]:
import numpy as np
arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [23]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [13]:
# ARGSORT ---> INDEX POSITIONS SORTED FROM LEAST --> GREATEST
# TOP 10 VALUES (10 GERATEST VALUES)
# LAST 10 VALUES of ARGSORT()
single_topic.argsort()[-10:] # grab the last 10 values of .argsort()

array([ 8209,  2257,  8127,  7877,  7225, 14491, 10984,  9049,  3797,
        8128], dtype=int64)

In [14]:
top_twenty_words = single_topic.argsort()[-20:]
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

stor
tæt
toilet
stort
lejemålet
opført
adgang
ca
ved
god
ligger
beliggende
lejlighed
køkken
kan
www
samt
m²
ejendommen
lejligheden


In [30]:
# Grab the highest probability words per topic

for i, topic in enumerate(LDA.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['m²', 'gulvvarme', 'www', 'stue', 'fra', 'udgang', 'bryggers', 'et', 'som', 'stort', 'køkken', 'stor', 'badeværelse', 'af', 'samt']




THE TOP 15 WORDS FOR TOPIC #1
['ca', 'om', 'ikke', 'mulighed', 'samt', 'har', 'det', 'den', 'kan', 'fra', 'ejendommen', 'som', 'm²', 'et', 'af']




THE TOP 15 WORDS FOR TOPIC #2
['stort', 'ejendommen', 'ca', 'det', 'køkken', 'badeværelse', 'som', 'm2', 'har', 'den', 'samt', 'huset', 'fra', 'af', 'et']




THE TOP 15 WORDS FOR TOPIC #3
['pa', 'flot', 'som', 'kvm', 'gode', 'ejendomme', 'ejendommen', 'et', 'samt', 'fra', 'har', 'c3', 'beliggende', 'af', 'lejemålet']




THE TOP 15 WORDS FOR TOPIC #4
['værelser', 'får', 'sig', 'også', 'jer', 'hvor', 'så', 'fra', 'har', 'som', 'det', 'kan', 'den', 'af', 'et']




THE TOP 15 WORDS FOR TOPIC #5
['store', 'gode', 'kan', 'man', 'plads', 'det', 'god', 'den', 'samt', 'som', 'af', 'fra', 'har', 'et', 'du']




THE TOP 15 WORDS FOR TOPIC #6
['du', 'ligger', 'så', 'sig', 'køkken', 'hv

In [33]:
dtm

<2500x14817 sparse matrix of type '<class 'numpy.int64'>'
	with 358349 stored elements in Compressed Sparse Row format>

In [36]:
topic_results = LDA.transform(dtm)
topic_results[0].round(2)

array([0.  , 0.12, 0.  , 0.  , 0.45, 0.42, 0.  ])

In [40]:
npr['text'][0]

0    I det populære Paarup udbydes her en dejlig vi...
Name: text, dtype: object

In [41]:
topic_results[0].argmax()

4

In [42]:
npr['text'] = topic_results.argmax(axis=1)
npr

text
0        4
1        5
2        5
3        5
4        3
...    ...
2495     4
2496     5
2497     5
2498     4
2499     2

[2500 rows x 1 columns]